export { Home as HomePage } from './home/home';
export { Profile as ProfilePage } from './profile/profile';
export { Tasks as TasksPage } from './tasks/tasks';
export { AccordionPage } from './accordion/accordion';
export { ChatPage } from './chat/chat';
export { TextValidator as TextValidatorPage } from './validator/text/TextValidator';
export { FormValidator as FormValidatorPage } from './validator/form/FormValidator';
export { GalleryPage } from './gallery/gallery';
export { FileManagerPage } from './file-manager/FileManager';
export { Table } from './table/Table';
export { MapPage } from './map/Map';
export { TileViewPage } from './tile-view/TileView';
export { TextBoxPage } from './text-box/TextBox';
export { HtmlEditorPage } from './html-editor/HtmlEditor';
export { CompanyTable } from './table/CompanyTable';
export { CompanyEmployeeTable } from './table/CompanyEmployeeTable';